# Project information
site_name: Docs
site_url: 'https://itjorgealves.github.io/mkdocs/'

# Repository
repo_name: 'itjorgealves/mkdocs'
repo_url: 'https://github.com/itjorgealves/mkdocs'
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.path
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.share
    # - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  #- typeset
  - blog

# Hooks

# Additional configuration

# Extensions
markdown_extensions:
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Annotations
  - attr_list
  - md_in_html
  - pymdownx.superfences
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
#  - Home: index.md
  - eJPT:
    - Introdution: eJPT/ejpt.md
    - Assessment Methodologies:
      - Information Gathering: eJPT/S1/C1/Information-Gathering.md
      - Footprinting & Scanning: eJPT/S1/C2/Footprinting-Scanning.md
      - Enumeration: eJPT/S1/C3/Enumeration.md
      - Vulnerability Assesment: eJPT/S1/C4/Vulnerability-Assesment.md
    - Host & Networking Auditing:
      - Auditing Fundamentals: eJPT/S2/C1/Auditing-Fundamentals.md
    - Host & Network Penetration Testing:
      - System/Host Based Attacks: eJPT/S3/C1/System-Host-Based-Attacks.md
      - Network-Based Attacks: eJPT/S3/C2/Network-Based-Attacks.md
      - The Metasploit Framework (MSF): eJPT/S3/C3/The-Metasploit-Framework-MSF.md
      - Exploitation: eJPT/S3/C4/Exploitation.md
      - Post-Exploitation: eJPT/S3/C5/Post-Exploitation.md
      - Social Engineering: eJPT/S3/C6/Social-Engineering.md
    - Web Application Penetration Testing:
      - Introduction to the Web and HTTP Protocol: eJPT/S4/C1/Introduction-to-the-Web-and-HTTP-Protocol.md
#  - Blog: blog/index.md

# Additional CSS
extra_css:
  - stylesheets/extra.css
