# Project information
site_name: Docs
site_url: 'https://itjorgealves.github.io/mkdocs/'

# Repository
repo_name: 'itjorgealves/mkdocs'
repo_url: 'https://github.com/itjorgealves/mkdocs'
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate # Code annotations
    - content.code.copy # Code copy button
    - content.code.select # Code selection button
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.path
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.share
    # - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto Condensed
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    #annotation: simple/youtube

# Plugins
plugins:
  - search
  #- typeset
  - blog

# Hooks

# Additional configuration

# Extensions
markdown_extensions:
  # General
  - attr_list
  - pymdownx.superfences
  # Admonitions
  - admonition
  - pymdownx.details
  # Annotations
  - md_in_html
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Icons and Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
#  - Home: index.md
  - eJPT:
    - Introduction: eJPT/Introduction.md
    - Assessment Methodologies:
      - Information Gathering: eJPT/S1-Assessment-Methodologies/C1/Information-Gathering.md
      - Footprinting & Scanning: eJPT/S1-Assessment-Methodologies/C2/Footprinting-Scanning.md
      - Enumeration: eJPT/S1-Assessment-Methodologies/C3/Enumeration.md
      - Vulnerability Assesment: eJPT/S1-Assessment-Methodologies/C4/Vulnerability-Assesment.md
    - Host & Networking Auditing:
      - Auditing Fundamentals: eJPT/S2-Host-Networking-Auditing/C1/Auditing-Fundamentals.md
    - Host & Network Penetration Testing:
      - System/Host Based Attacks: eJPT/S3-Host-Network-Penetration-Testing/C1/System-Host-Based-Attacks.md
      - Network-Based Attacks: eJPT/S3-Host-Network-Penetration-Testing/C2/Network-Based-Attacks.md
      - The Metasploit Framework (MSF): eJPT/S3-Host-Network-Penetration-Testing/C3/The-Metasploit-Framework-MSF.md
      - Exploitation: eJPT/S3-Host-Network-Penetration-Testing/C4/Exploitation.md
      - Post-Exploitation: eJPT/S3-Host-Network-Penetration-Testing/C5/Post-Exploitation.md
      - Social Engineering: eJPT/S3-Host-Network-Penetration-Testing/C6/Social-Engineering.md
    - Web Application Penetration Testing:
      - Introduction to the Web and HTTP Protocol: eJPT/S4-Web-Application-Penetration-Testing/C1/Introduction-to-the-Web-and-HTTP-Protocol.md
#  - Blog: blog/index.md

# Additional CSS
extra_css:
  - stylesheets/extra.css
